import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-primary backdrop-blur">
          <nav className="container max-w-screen-2xl p-2">
            <menu className="flex items-center gap-4 lg:gap-6">
              <li>
                <Link
                  href="projects"
                  className="transition-colors hover:text-foreground/80"
                >
                  projects
                </Link>
              </li>
              <li>
                <Link
                  href="stories"
                  className="transition-colors hover:text-foreground/80"
                >
                  stories
                </Link>
              </li>
            </menu>
          </nav>
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
